version: '3.3'

services:
  auth:
    container_name: auth
    build: .
    volumes:
      - auth_data:/usr/share/auth/data
    networks:
      main:
    ports:
      - "8000:8000"
    restart: always


networks:
  main:

volumes:
  auth_data: